In [360]:

from EmQuantAPI import *
import time
loginresult = c.start( )
#loginresult为c.EmQuantData类型数据
print (loginresult)
# 2022-06-22 08:35:12
# 沪深股票 均价 成交量 成交金额 收盘价
data=c.csd("000972.SZ","AVERAGE,VOLUME,AMOUNT,HIGHLIMIT","2021-05-22","2022-06-21","period=1,adjustflag=1,curtype=1,order=1,market=CNSESZ,order=1,Ispandas=1,RowIndex=0")
print(data)

# data['DATES'][0]=time.mktime(data['DATES'])

[EmQuantAPI Python] [Em_Info][2022-06-22 09:36:32]:your account is online, not need login in again!

ErrorCode=0, ErrorMsg=success, Data={}
         CODES       DATES AVERAGE    VOLUME       AMOUNT HIGHLIMIT
0    000972.SZ  2021/05/24    1.96   2104765    4125339.4         是
1    000972.SZ  2021/05/25  2.0449  12670180  25908938.01         是
2    000972.SZ  2021/05/26  2.0475   9612577  19681498.85         否
3    000972.SZ  2021/05/27  2.0721   4559512   9447834.24         是
4    000972.SZ  2021/05/28  2.1966   3855713   8469400.73         是
..         ...         ...     ...       ...          ...       ...
257  000972.SZ  2022/06/15  2.6581  11825430   31433617.2         否
258  000972.SZ  2022/06/16  2.6797  12971207  34758900.26         否
259  000972.SZ  2022/06/17  2.6483   7020200   18591724.0         否
260  000972.SZ  2022/06/20  2.6935   5553300   14957960.0         否
261  000972.SZ  2022/06/21  2.6764   2751101   7362956.66         否

[262 rows x 6 columns]


In [361]:
for i in range(0,len(data['DATES'])):
    timeArray = time.strptime(data['DATES'][i], "%Y/%m/%d")
    timeStamp = int(time.mktime(timeArray))
    data['DATES'][i]=timeStamp

# print(data['DATES'])


X=data.iloc[:, 1:5].to_numpy()
Y=data.iloc[:,5].to_numpy()
print(X)
print(Y)


import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split as TTS

Xtrain, Xtest, Ytrain, Ytest = TTS(X, Y, test_size=0.4, random_state=420)
Xtest_extra = [ [1651075200 ,1.7149 ,5298700 ,9086902.0]]
Ytest_extra = [['否']]
print(Xtrain)
print(Ytrain)
# print(Xtest)

[[1621785600 1.96 2104765 4125339.4]
 [1621872000 2.0449 12670180 25908938.01]
 [1621958400 2.0475 9612577 19681498.85]
 ...
 [1655395200 2.6483 7020200 18591724.0]
 [1655654400 2.6935 5553300 14957960.0]
 [1655740800 2.6764 2751101 7362956.66]]
['是' '是' '否' '是' '是' '是' '否' '是' '否' '否' '否' '否' '否' '否' '否' '是' '否' '否'
 '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '是' '否' '否' '否'
 '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否'
 '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否'
 '否' '否' '是' '否' '是' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否'
 '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否'
 '否' '是' '是' '是' '是' '是' '否' '否' '否' '否' '是' '否' '否' '否' '否' '是' '否' '是'
 '否' '否' '否' '是' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '是'
 '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否'
 '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否' '否'
 '否' '否' '否' '否' '否' '否'

In [362]:
from sklearn.neural_network import MLPClassifier as ANN
from time import time
import matplotlib.pyplot as plt
ann = ANN(hidden_layer_sizes=(100,), random_state=420).fit(Xtrain, Ytrain)


In [363]:
print("==========================================")
print("准确率为：", ann.score(Xtest, Ytest))
print("==========================================")

准确率为： 0.9142857142857143


In [364]:
print("==========================================")
print("测试数据[1651075200 ,1.7149 ,5298700 ,9086902.0]")
print(ann.predict([[1651075200 ,1.7149 ,5298700 ,9086902.0]]))
print("==========================================")

测试数据[1651075200 ,1.7149 ,5298700 ,9086902.0]
['否']
