In [277]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split as TTS

data = pd.read_csv(
    r"C:\Users\96361\iCloudDrive\数据挖掘实践-胡仕成\A\continuousData\Sampledata-continuous.CSV", encoding='GBK')


print(data)

    HS_AGE  VAS_AR_FLAG  AVG_USAGE_DAYS  AVG_BILL_AMT  AVG_MINS  AVG_CALL  \
0     0.12            1            0.99          0.34      0.31      0.25   
1     1.00            0            0.29          0.00      0.03      0.01   
2     0.35            0            1.00          0.36      0.47      0.47   
3     0.00            0            0.98          0.18      0.19      0.18   
4     0.55            0            0.84          0.10      0.05      0.06   
5     0.00            0            1.00          0.14      0.08      0.09   
6     0.35            1            0.98          0.21      0.12      0.11   
7     0.07            0            0.53          0.11      0.02      0.01   
8     0.00            0            0.40          0.05      0.01      0.01   
9     0.07            1            0.71          0.19      0.08      0.09   
10    0.00            0            0.98          0.22      0.14      0.19   
11    0.12            0            0.79          0.04      0.04      0.04   

In [278]:
X_train = data.iloc[:, :7].to_numpy()
y_train = data.iloc[:, 7].to_numpy()
Xtrain, Xtest, Ytrain, Ytest = TTS(
    X_train, y_train, test_size=0.3, random_state=420)

print(X_train,type(X_train))

[[0.12 1.   0.99 0.34 0.31 0.25 0.  ]
 [1.   0.   0.29 0.   0.03 0.01 0.  ]
 [0.35 0.   1.   0.36 0.47 0.47 0.03]
 [0.   0.   0.98 0.18 0.19 0.18 0.01]
 [0.55 0.   0.84 0.1  0.05 0.06 0.  ]
 [0.   0.   1.   0.14 0.08 0.09 0.  ]
 [0.35 1.   0.98 0.21 0.12 0.11 0.  ]
 [0.07 0.   0.53 0.11 0.02 0.01 0.25]
 [0.   0.   0.4  0.05 0.01 0.01 0.07]
 [0.07 1.   0.71 0.19 0.08 0.09 0.1 ]
 [0.   0.   0.98 0.22 0.14 0.19 0.  ]
 [0.12 0.   0.79 0.04 0.04 0.04 0.02]
 [0.   0.   0.96 0.17 0.44 0.1  0.  ]
 [0.03 0.   0.76 0.05 0.09 0.04 0.08]
 [0.22 1.   0.95 0.19 0.15 0.09 0.01]
 [0.62 0.   1.   0.28 0.22 0.21 1.  ]
 [0.18 1.   1.   0.27 0.21 0.22 0.  ]
 [0.45 0.   1.   0.16 0.15 0.15 0.04]
 [0.17 0.   0.99 0.09 0.13 0.1  0.04]
 [0.   0.   0.99 0.19 0.16 0.14 0.  ]
 [0.02 1.   0.91 0.16 0.11 0.05 0.02]
 [0.05 1.   0.89 0.37 0.14 0.1  0.2 ]
 [0.57 1.   1.   1.   1.   1.   0.  ]
 [0.33 0.   0.11 0.   0.   0.   0.  ]
 [0.22 1.   0.66 0.94 0.07 0.04 0.02]
 [0.02 0.   0.46 0.04 0.08 0.02 0.  ]
 [0.32 1.   

In [279]:
print(Xtest,type(Xtest))

[[0.07 1.   0.71 0.19 0.08 0.09 0.1 ]
 [0.07 0.   0.53 0.11 0.02 0.01 0.25]
 [0.17 0.   0.99 0.09 0.13 0.1  0.04]
 [0.18 1.   1.   0.27 0.21 0.22 0.  ]
 [1.   0.   0.29 0.   0.03 0.01 0.  ]
 [0.57 1.   1.   1.   1.   1.   0.  ]
 [0.12 0.   0.72 0.01 0.02 0.02 0.  ]
 [0.22 1.   0.66 0.94 0.07 0.04 0.02]
 [0.   0.   0.96 0.17 0.44 0.1  0.  ]] <class 'numpy.ndarray'>


In [280]:
Xtest_extra = [[0.12,	0, 0.72,	0.01, 0.02,	0.02,	0]]
Ytest_extra = [['2G']]

clf = GaussianNB()
# 拟合数据
clf.fit(Xtrain, Ytrain)

GaussianNB()

In [281]:

print("==========================================")
print("测试准确率为:")
print(clf.score(Xtest, Ytest))
print("==========================================")

print("==========================================")
print("测试数据[0.12,0, 0.72,0.01,0.02,0.02,0]")
print("分类结果CUSTOMER_TYPE:"+str(clf.predict([[0.12,0, 0.72,0.01,0.02,0.02,0]])))
print("==========================================")


测试准确率为:
0.3333333333333333
测试数据[0.12,0, 0.72,0.01,0.02,0.02,0]
分类结果CUSTOMER_TYPE:['2G']
