In [40]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB

data = pd.read_csv(r"C:\Users\96361\iCloudDrive\数据挖掘实践-胡仕成\A\continuousData\Sampledata-continuous.CSV",encoding='GBK')

X_train=data.iloc[:,:7].to_numpy()
y_train=data.iloc[:,7].to_numpy()
print(X_train)
print(y_train)

[[0.12 1.   0.99 0.34 0.31 0.25 0.  ]
 [1.   0.   0.29 0.   0.03 0.01 0.  ]
 [0.35 0.   1.   0.36 0.47 0.47 0.03]
 [0.   0.   0.98 0.18 0.19 0.18 0.01]
 [0.55 0.   0.84 0.1  0.05 0.06 0.  ]
 [0.   0.   1.   0.14 0.08 0.09 0.  ]
 [0.35 1.   0.98 0.21 0.12 0.11 0.  ]
 [0.07 0.   0.53 0.11 0.02 0.01 0.25]
 [0.   0.   0.4  0.05 0.01 0.01 0.07]
 [0.07 1.   0.71 0.19 0.08 0.09 0.1 ]
 [0.   0.   0.98 0.22 0.14 0.19 0.  ]
 [0.12 0.   0.79 0.04 0.04 0.04 0.02]
 [0.   0.   0.96 0.17 0.44 0.1  0.  ]
 [0.03 0.   0.76 0.05 0.09 0.04 0.08]
 [0.22 1.   0.95 0.19 0.15 0.09 0.01]
 [0.62 0.   1.   0.28 0.22 0.21 1.  ]
 [0.18 1.   1.   0.27 0.21 0.22 0.  ]
 [0.45 0.   1.   0.16 0.15 0.15 0.04]
 [0.17 0.   0.99 0.09 0.13 0.1  0.04]
 [0.   0.   0.99 0.19 0.16 0.14 0.  ]
 [0.02 1.   0.91 0.16 0.11 0.05 0.02]
 [0.05 1.   0.89 0.37 0.14 0.1  0.2 ]
 [0.57 1.   1.   1.   1.   1.   0.  ]
 [0.33 0.   0.11 0.   0.   0.   0.  ]
 [0.22 1.   0.66 0.94 0.07 0.04 0.02]
 [0.02 0.   0.46 0.04 0.08 0.02 0.  ]
 [0.32 1.   

In [41]:
from sklearn.model_selection import train_test_split as TTS

Xtrain, Xtest, Ytrain, Ytest = TTS(X_train, y_train, test_size=0.3, random_state=420)
Xtest_extra = [[0.12,	0, 0.72,	0.01, 0.02,	0.02,	0]]
Ytest_extra = [['2G']]
print(X_train)
print(Xtest)

[[0.12 1.   0.99 0.34 0.31 0.25 0.  ]
 [1.   0.   0.29 0.   0.03 0.01 0.  ]
 [0.35 0.   1.   0.36 0.47 0.47 0.03]
 [0.   0.   0.98 0.18 0.19 0.18 0.01]
 [0.55 0.   0.84 0.1  0.05 0.06 0.  ]
 [0.   0.   1.   0.14 0.08 0.09 0.  ]
 [0.35 1.   0.98 0.21 0.12 0.11 0.  ]
 [0.07 0.   0.53 0.11 0.02 0.01 0.25]
 [0.   0.   0.4  0.05 0.01 0.01 0.07]
 [0.07 1.   0.71 0.19 0.08 0.09 0.1 ]
 [0.   0.   0.98 0.22 0.14 0.19 0.  ]
 [0.12 0.   0.79 0.04 0.04 0.04 0.02]
 [0.   0.   0.96 0.17 0.44 0.1  0.  ]
 [0.03 0.   0.76 0.05 0.09 0.04 0.08]
 [0.22 1.   0.95 0.19 0.15 0.09 0.01]
 [0.62 0.   1.   0.28 0.22 0.21 1.  ]
 [0.18 1.   1.   0.27 0.21 0.22 0.  ]
 [0.45 0.   1.   0.16 0.15 0.15 0.04]
 [0.17 0.   0.99 0.09 0.13 0.1  0.04]
 [0.   0.   0.99 0.19 0.16 0.14 0.  ]
 [0.02 1.   0.91 0.16 0.11 0.05 0.02]
 [0.05 1.   0.89 0.37 0.14 0.1  0.2 ]
 [0.57 1.   1.   1.   1.   1.   0.  ]
 [0.33 0.   0.11 0.   0.   0.   0.  ]
 [0.22 1.   0.66 0.94 0.07 0.04 0.02]
 [0.02 0.   0.46 0.04 0.08 0.02 0.  ]
 [0.32 1.   

In [42]:
from sklearn.neural_network import MLPClassifier as DNN
from sklearn.model_selection import cross_val_score as cv
from sklearn.tree import DecisionTreeClassifier as DTC
from time import time
import datetime

dnn = DNN(hidden_layer_sizes=(100,), random_state=420).fit(Xtrain, Ytrain)


c:\ProgramData\Anaconda3\envs\dm\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [43]:
print("==========================================")
print("准确率为：", dnn.score(Xtest, Ytest))


print("==========================================")

print("==========================================")
print("测试数据[0.12,0, 0.72,0.01,0.02,0.02,0]")
if (dnn.score(Xtest_extra, Ytest_extra) == 1.0):
    print("分类结果CUSTOMER_TYPE:2G")
    # 0:yes 1:no
else:
    print("分类结果CUSTOMER_TYPE:3G")
print("==========================================")


准确率为： 0.5555555555555556
测试数据[0.12,0, 0.72,0.01,0.02,0.02,0]
分类结果CUSTOMER_TYPE:2G
