In [74]:

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
# data = pd.read_csv(r"C:\Users\96361\Desktop\selflearning\github\Machine-Learning\01 决策树课件数据源码\data.csv",index_col = 0)
data = pd.read_csv(r"C:\Users\96361\iCloudDrive\数据挖掘实践-胡仕成\A\discreteData\Sampledata-discrete.CSV",encoding='GBK')

# data.head()
# data.info()
#将分类变量转换为数值型变量

#将二分类变量转换为数值型变量
#astype能够将一个pandas对象转换为某种类型，和apply(int(x))不同，astype可以将文本类转换为数字，用这个方式可以很便捷地将二分类特征转换为0~1
data["student"] = (data["student"]== "no").astype("int")
data["buys_computer"] = (data["buys_computer"]== "no").astype("int")
data["credit_rating"] = (data["credit_rating"]== "fair").astype("int")

#将三分类变量转换为数值型变量
labels = data["age"].unique().tolist()
data["age"] = data["age"].apply(lambda x: labels.index(x))

labels2 = data["income"].unique().tolist()
data["income"] = data["income"].apply(lambda x: labels2.index(x))

# #查看处理后的数据集
data.head()
X = data.iloc[:,data.columns != "buys_computer"]
y = data.iloc[:,data.columns == "buys_computer"]
# print(data)
# print(data["age"])
print(data.iloc[:,:4].to_numpy())
print(data.iloc[:,4].to_numpy())

[[0 0 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [2 1 1 1]
 [2 2 0 1]
 [2 2 0 0]
 [1 2 0 0]
 [0 1 1 1]
 [0 2 0 1]
 [2 1 0 1]
 [0 1 0 0]
 [1 1 1 0]
 [1 0 0 1]
 [2 1 1 0]
 [0 1 1 1]
 [0 2 0 0]
 [1 1 0 1]
 [1 0 1 0]
 [1 2 1 0]
 [2 2 0 0]
 [2 0 1 1]
 [1 1 1 1]]
[1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0]


In [75]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
# X=np.array(data.iloc[:,:4])
# X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
# Y = np.array([1, 1, 1, 2, 2, 2])
# print(X,type(X))
# print(Y,type(Y))
X_train=data.iloc[:,:4].to_numpy()
y_train=data.iloc[:,4].to_numpy()
X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2,random_state=0)

print(X_train,type(X_train))
print(X_test,type(X_test))


[[1 1 1 1]
 [1 1 1 0]
 [2 2 0 0]
 [0 2 0 1]
 [1 2 0 0]
 [1 1 0 1]
 [2 2 0 1]
 [1 0 1 1]
 [2 2 0 0]
 [1 0 1 0]
 [2 1 0 1]
 [0 1 1 1]
 [1 2 1 0]
 [2 1 1 1]
 [0 0 1 1]
 [0 2 0 0]
 [1 0 0 1]] <class 'numpy.ndarray'>
[[2 0 1 1]
 [0 1 0 0]
 [0 1 1 1]
 [2 1 1 0]
 [0 0 1 0]] <class 'numpy.ndarray'>


In [76]:
clf = GaussianNB()
# 拟合数据
clf.fit(X_train, y_train)


GaussianNB()

In [77]:
print("==========================================")
print("测试准确率为:")
print(clf.score(X_test, y_test))
print("==========================================")

测试准确率为:
0.6


In [78]:
print("==========================================")
print("测试数据[31...40,medium,no,fair]")
# 0:yes 1:no
if(clf.predict([[1,1,1,1]])[0]==0):
    print("分类结果buy_computers=yes")
else:
    print("分类结果buy_computers=no")
print("==========================================")


测试数据[31...40,medium,no,fair]
分类结果buy_computers=yes
