In [59]:

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
# 导入决策树分类器
from sklearn.tree import DecisionTreeClassifier
# 导入分割数据集的方法
from sklearn.model_selection import train_test_split
# 导入科学计算包
import numpy as np

data = pd.read_csv(r"C:\Users\96361\iCloudDrive\数据挖掘实践-胡仕成\A\discreteData\Sampledata-discrete.CSV",encoding='GBK')

data.head()



age  income student credit_rating buys_computer
0    30    high      no          fair            no
1    30    high      no     excellent            no
2  3140    high      no          fair           yes
3    40  medium      no          fair           yes
4    40     low     yes          fair           yes

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            22 non-null     int64 
 1   income         22 non-null     object
 2   student        22 non-null     object
 3   credit_rating  22 non-null     object
 4   buys_computer  22 non-null     object
dtypes: int64(1), object(4)
memory usage: 1008.0+ bytes


In [63]:
#将分类变量转换为数值型变量

#将二分类变量转换为数值型变量
#astype能够将一个pandas对象转换为某种类型，和apply(int(x))不同，astype可以将文本类转换为数字，用这个方式可以很便捷地将二分类特征转换为0~1
data["student"] = (data["student"]== "no").astype("int")
data["buys_computer"] = (data["buys_computer"]== "no").astype("int")
data["credit_rating"] = (data["credit_rating"]== "fair").astype("int")

#将三分类变量转换为数值型变量
labels = data["age"].unique().tolist()
data["age"] = data["age"].apply(lambda x: labels.index(x))

labels2 = data["income"].unique().tolist()
data["income"] = data["income"].apply(lambda x: labels2.index(x))

# #查看处理后的数据集
data.head()
X = data.iloc[:,data.columns != "buys_computer"]
y = data.iloc[:,data.columns == "buys_computer"]
X_train=data.iloc[:,:4].to_numpy()
y_train=data.iloc[:,4].to_numpy()
print(X_train)
print(y_train)

X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2,random_state=0)



[[0 0 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [2 1 1 1]
 [2 2 0 1]
 [2 2 0 0]
 [1 2 0 0]
 [0 1 1 1]
 [0 2 0 1]
 [2 1 0 1]
 [0 1 0 0]
 [1 1 1 0]
 [1 0 0 1]
 [2 1 1 0]
 [0 1 1 1]
 [0 2 0 0]
 [1 1 0 1]
 [1 0 1 0]
 [1 2 1 0]
 [2 2 0 0]
 [2 0 1 1]
 [1 1 1 1]]
[1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0]


In [64]:
# 调用Gini算法
tree_model=DecisionTreeClassifier(criterion="gini")
# 拟合
print(tree_model.fit(X_train,y_train))

DecisionTreeClassifier()


In [60]:
# print(predict_result)
# 0:yes 1:no
print("==========================================")
print("测试准确率为:")
print(tree_model.score(X_test,y_test))

测试准确率为:
0.6


In [61]:
# 给出一组数据预测分类
CUSTOMER_TYPE=np.array([[1,1,1,1]])
predict_result=tree_model.predict(CUSTOMER_TYPE)
print("测试数据[31...40,medium,no,fair]")
if(predict_result[0]==0):
    print("分类结果buy_computers=yes")
else:
    print("分类结果buy_computers=no")
print("==========================================")


测试数据[31...40,medium,no,fair]
分类结果buy_computers=yes
