In [1]:

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
# data = pd.read_csv(r"C:\Users\96361\Desktop\selflearning\github\Machine-Learning\01 决策树课件数据源码\data.csv",index_col = 0)
data = pd.read_csv(r"C:\Users\96361\iCloudDrive\数据挖掘实践-胡仕成\A\discreteData\Sampledata-discrete.CSV",encoding='GBK')

print(data)
# data.head()
# data.info()

     age  income student credit_rating buys_computer
0     30    high      no          fair            no
1     30    high      no     excellent            no
2   3140    high      no          fair           yes
3     40  medium      no          fair           yes
4     40     low     yes          fair           yes
5     40     low     yes     excellent            no
6   3140     low     yes     excellent           yes
7     30  medium      no          fair            no
8     30     low     yes          fair           yes
9     40  medium     yes          fair           yes
10    30  medium     yes     excellent           yes
11  3140  medium      no     excellent           yes
12  3140    high     yes          fair           yes
13    40  medium      no     excellent            no
14    30  medium      no          fair            no
15    30     low     yes     excellent           yes
16  3140  medium     yes          fair           yes
17  3140    high      no     excellent        

In [2]:
import numpy as np
from sklearn.neural_network import MLPClassifier as DNN
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score as cv
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.model_selection import train_test_split as TTS
from time import time
import datetime
#将分类变量转换为数值型变量
#将二分类变量转换为数值型变量
#astype能够将一个pandas对象转换为某种类型，和apply(int(x))不同，astype可以将文本类转换为数字，用这个方式可以很便捷地将二分类特征转换为0~1
data["student"] = (data["student"]== "no").astype("int")
data["buys_computer"] = (data["buys_computer"]== "no").astype("int")
data["credit_rating"] = (data["credit_rating"]== "fair").astype("int")

#将三分类变量转换为数值型变量
labels = data["age"].unique().tolist()
data["age"] = data["age"].apply(lambda x: labels.index(x))

labels2 = data["income"].unique().tolist()
data["income"] = data["income"].apply(lambda x: labels2.index(x))

# #查看处理后的数据集
# data.head()
X = data.iloc[:,data.columns != "buys_computer"]
y = data.iloc[:,data.columns == "buys_computer"]

X_train=data.iloc[:,:4].to_numpy()
y_train=data.iloc[:,4].to_numpy()
print(X_train)
print(y_train)
# data = load_breast_cancer()
# X = data.data
# y = data.target
Xtrain, Xtest, Ytrain, Ytest = TTS(X_train,y_train,test_size=0.3,random_state=420)

Xtest_extra=[[1,1,1,1]]
Ytest_extra=[[1]]
# print(Ytest)


[[0 0 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [2 1 1 1]
 [2 2 0 1]
 [2 2 0 0]
 [1 2 0 0]
 [0 1 1 1]
 [0 2 0 1]
 [2 1 0 1]
 [0 1 0 0]
 [1 1 1 0]
 [1 0 0 1]
 [2 1 1 0]
 [0 1 1 1]
 [0 2 0 0]
 [1 1 0 1]
 [1 0 1 0]
 [1 2 1 0]
 [2 2 0 0]
 [2 0 1 1]
 [1 1 1 1]]
[1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0]


In [3]:
times = time()
times = time()
dnn = DNN(hidden_layer_sizes=(100,),random_state=420).fit(Xtrain,Ytrain)
# print(dnn.score)


c:\ProgramData\Anaconda3\envs\dm\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [4]:
#使用重要参数n_layers_，得出层数
# print("n_layers_：",dnn.n_layers_)

print("==========================================")
print("准确率为：",dnn.score(Xtest,Ytest))

print("==========================================")

准确率为： 0.7142857142857143


In [5]:
print("==========================================")
print("测试数据[31...40,medium,no,fair]")
if(dnn.score(Xtest_extra,Ytest_extra)==1.0):
    print("buys_computer的预测结果:no")
    # 0:yes 1:no
else:
    print("buys_computer的预测结果：yes")
print("==========================================")
    

测试数据[31...40,medium,no,fair]
buys_computer的预测结果:no
